/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-05-09 22:53:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/xxxx/Desktop/Zweit_WEB/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/zweit_web_projekt/WEB-INF/lib/struts2-core-2.5.20.jar!/META-INF/struts-tags.tld", Long.valueOf(1547031768000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.20.jar", Long.valueOf(1547031836000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Deutsch lernen</title>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link href=\"css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Custom styles for this template-->\r\n");
      out.write("<link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- NAVBAR Start-->\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-dark bg-gradient-primary\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a class=\"navbar-brand-image rotate-n-15\" href=\"#\"><img\r\n");
      out.write("\t\t\t\tsrc=\"img/logo.png\"></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSite\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto my-1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mr-2 mt-1 mb-1\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn-sm btn-success\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#modallogin\">Sign in</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mt-1 mb-1\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn-sm btn-success\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#modalRegistro\">Sign up</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- NAVBAR End-->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-12 text-center mt-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h1 class=\"display-4\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-capsules text-primary\"></i> Título slide 4\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<p>Texto slide 4</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row justify-content-sm-center mt-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"card mb-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img class=\"card-img-top\" src=\"img/img-tibia-2.jpg\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"h-25 p-3\" style=\"background-color: #eee;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\" card-title\">Rush do 50 ao 100</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Ñ sei ainda</h6>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">Mas certamente eu chego lá. kkkkkk kkkkk.\r\n");
      out.write("\t\t\t\t\t\t\tEstou esperando aquele rush maroto do lvl 500. Possivelmente\r\n");
      out.write("\t\t\t\t\t\t\tchegaremos no lvl 1000. Guiiii guiiii tik .. tik... tik.. Guiii\r\n");
      out.write("\t\t\t\t\t\t\tGuiiii guiiii tik .. tik... tik.. Guiii</p>\r\n");
      out.write("\t\t\t\t\t\t<!-- Lista dentro dos cards-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-group list-group-flush\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\">Up ontem foi nervoso</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\">Mas morremos logo d cara</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\">mas foram 9 lvls ganhos</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-footer text-muted\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"card-link\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#siteModal-03\">veja o Modal-03</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"card mb-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img class=\"card-img-top\" src=\"img/img-tibia-1.jpg\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"h-25 p-3\" style=\"background-color: #eee;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\" card-title\">Estudando Alemão</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Mitos sobre\r\n");
      out.write("\t\t\t\t\t\t\t\tAlemanha</h6>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">Hitler na verdade era apenas um criador\r\n");
      out.write("\t\t\t\t\t\t\tde Curio. todas essas coisas que falam a respeito do Fuher são\r\n");
      out.write("\t\t\t\t\t\t\tmentiras criadas pela midia Comunista . Comandada pelo Lulão e\r\n");
      out.write("\t\t\t\t\t\t\tDilminha.</p>\r\n");
      out.write("\t\t\t\t\t\t<!-- Lista dentro dos cards-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-group list-group-flush\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\">Up ontem foi nervoso</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\">Mas morremos logo d cara</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\">mas foram 9 lvls ganhos</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-footer text-muted\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"card-link\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#siteModal-02\">veja o Modal-02</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"card mb-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img class=\"card-img-top\" src=\"img/img-tibia-3.jpg\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"h-25 p-3\" style=\"background-color: #eee;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\" card-title\">Tibião da Maldade</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"card-subtitle mb-2 text-muted\">Morrendo em Thais</h6>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">Treino de Tilapia do Nilo. Pode ser\r\n");
      out.write("\t\t\t\t\t\t\tPerigoso. Pois pks low lvl podem lhe matar AFK. Be carefull. =)\r\n");
      out.write("\t\t\t\t\t\t\tUse spears e Hams para baratear o up de skill. #Dilma livre Lula\r\n");
      out.write("\t\t\t\t\t\t\tpreso.</p>\r\n");
      out.write("\t\t\t\t\t\t<!-- Lista dentro dos cards-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-group list-group-flush\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\">Up ontem foi nervoso</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\">Mas morremos logo d cara</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-group-item\">mas foram 9 lvls ganhos</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-footer text-muted\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"card-link\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#siteModal\">veja o Modal</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- JUMBOTRON + NAV PILLS-->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"jumbotron jumbotron-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h1 class=\"display-4\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-bed text-primary\"></i>Nav Pills\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t<p>Gwent ñ e ruim apenas está cheio de bugs</p>\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-pills justify-content-center\" id=\"pills-nav\"\r\n");
      out.write("\t\t\t\t\t\trole=\"tablist\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"nav-pills-01\" data-toggle=\"pill\" href=\"#nav-item-01\">Menu\r\n");
      out.write("\t\t\t\t\t\t\t\t01</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" id=\"nav-pills-01\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"pill\" href=\"#nav-item-02\">Menu 03</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" id=\"nav-pills-01\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"pill\" href=\"#nav-item-03\">Menu 02</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" id=\"nav-pills-01\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"pill\" href=\"#nav-item-03\">Menu 04</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-content mt-4\" id=\"nav-pills-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-pane fade show active\" id=\"nav-item-01\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"tabpanel\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"embed-responsive embed-responsive-16by9\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<iframe class=\"embed-resposive-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.youtube.com/embed/RMRQrdjxaKg\"></iframe>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>02... cagudoso... Era uma vez um papai noel mais magro q\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tum doberman N havia nenhum coelho da pascoa em sua sacola de\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpresentes</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-pane fade\" id=\"nav-item-02\" role=\"tabpanel\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"embed-responsive embed-responsive-16by9\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<iframe class=\"embed-resposive-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.youtube.com/embed/373AKueRbKs\"></iframe>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>02... cagudoso... Era uma vez um papai noel mais magro q\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tum doberman N havia nenhum coelho da pascoa em sua sacola de\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpresentes</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-pane fade\" id=\"nav-item-03\" role=\"tabpanel\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"embed-responsive embed-responsive-16by9\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<iframe class=\"embed-resposive-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.youtube.com/embed/VYndXT_RiMA\"></iframe>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>02... cagudoso... Era uma vez um papai noel mais magro q\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tum doberman N havia nenhum coelho da pascoa em sua sacola de\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpresentes</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-pane fade\" id=\"nav-item-04\" role=\"tabpanel\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"embed-responsive embed-responsive-16by9\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<iframe class=\"embed-resposive-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.youtube.com/embed/VYndXT_RiMA\"></iframe>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>02... cagudoso... Era uma vez um papai noel mais magro q\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tum doberman N havia nenhum coelho da pascoa em sua sacola de\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpresentes</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h1 class=\"display-4\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-id-card text-primary\"></i>formulário\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row justify-content-center mb-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-12 col-md-10 col-lg-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputName\">Nome</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputName\" placeholder=\"Nome\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputSobrenome\">Sobrenome</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputSobrenome\" placeholder=\"Sobrenome\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row col-sm-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"inputEndereço\">Endereço</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputEndereço\" placeholder=\"Endereço\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row col-sm-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"inputCidade\">Cidade</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputCidade\" placeholder=\"Cidade\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"inputEstado\">Estado</label> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputEstado\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option selected>Escolha...</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Acre (AC)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Alagoas (AL)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Amapá (AP)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Amazonas (AM)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Bahia (BA)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Ceará (CE)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Distrito Federal (DF)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Espírito Santo (ES)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Goiás (GO)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Maranhão (MA)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Mato Grosso (MT)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Mato Grosso do Sul (MS)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Minas Gerais (MG)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Pará (PA)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Pará (PA)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Paraíba (PB)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Paraná (PR</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Pernambuco (PE)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Piauí (PI)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Rio de Janeiro (RJ)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Rio Grande do Norte (RN)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Rio Grande do Sul (RS)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Rondônia (RO)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Roraima (RR)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Santa Catarina (SC)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>São Paulo (SP)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Sergipe (SE)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Tocantins (TO)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"inputCEP\">CEP</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputCEP\" placeholder=\"CEP\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-sm-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"form-check-label\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-check-input\" type=\"checkbox\">Desejo receber\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnovidades por e-mail.\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row col-sm-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\">Enviar</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-warning ml-2\" title=\"Header\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"popover\" data-placement=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-content=\"ñ posso t ajudar com isso!\">Ajuda</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center \">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-12 mt-4\">\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h3>Curso</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<p>O diário destacou a segurança oferecida pelo brasileiro,\r\n");
      out.write("\t\t\t\t\t\tespecialmente nesta reta final de temporada, e salientou a</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<p>maneira como ele tranquilizou os torcedores ingleses após o\r\n");
      out.write("\t\t\t\t\t\t\"trauma\" sofrido com o alemão Karius, na final da última Liga dos\r\n");
      out.write("\t\t\t\t\t\tCampeões, contra o Real Madrid</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h3>Biscoitos</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"list-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"list-group-item list-group-item-action\">Barceloa</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"list-group-item list-group-item-action\">Santos</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"list-group-item list-group-item-action\">Liverpool</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"list-group-item list-group-item-action\">Drogas</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h3>Tonel de Chorume</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group-vertical btn-block btn-group-lg\" role=\"group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-outline-primary\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fab fa-facebook-square\"></i>Facebook</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-outline-info\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fab fa-twitter\"></i>Twitter</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-outline-warning \" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fab fa-instagram\"></i>Instagran</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-12 mt-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<blockquote class=\"blockquote text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mb-0\">Vlww FLWWW.....</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<footer class=\"blockquote-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t100% learned <cite title=\"Source Title\">Bebum do Bar da\r\n");
      out.write("\t\t\t\t\t\t\t\tEsquina</cite>\r\n");
      out.write("\t\t\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t\t</blockquote>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- MODAL's -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 01 - MODAL Register -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal\" id=\"modalRegistro\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-sm\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\">Sign Up</h5>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form class=\"modal-body\" action=\"signUp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control empty mb-2\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"&#xf2bd  Login\" name=\"usuarioForm.login\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control empty mb-2\" type=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"&#xf199  E-mail\" name=\"usuarioForm.email\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control empty mb-2\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"&#xf084  Password\" name=\"usuarioForm.password\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control empty mb-2\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"&#xf084  Confirme Password\" name=\"\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary col-12 mt-3\">Register</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 02 - MODAL Login -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal\" id=\"modallogin\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-sm\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\">Sign Up</h5>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form class=\"modal-body\" action=\"login\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control empty mb-2\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"&#xf2bd  Login\" name=\"usuarioForm.login\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control empty mb-2\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"&#xf084  Password\" name=\"usuarioForm.password\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"form-check-label mb-2\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-check-input\" type=\"checkbox\">Lembrar senha\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary col-12\">Sign\r\n");
      out.write("\t\t\t\t\t\t\tIn</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"btn-sm btn-fail\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#\">Esqueceu sua senha?</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Optional JavaScript -->\r\n");
      out.write("\t<!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Core plugin JavaScript-->\r\n");
      out.write("\t<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for all pages-->\r\n");
      out.write("\t<script src=\"js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page level plugins -->\r\n");
      out.write("\t<script src=\"vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page level custom scripts -->\r\n");
      out.write("\t<script src=\"js/demo/chart-area-demo.js\"></script>\r\n");
      out.write("\t<script src=\"js/demo/chart-pie-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("          $('[data-toggle=\"popover\"]').popover();   \r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
